writer_task:
  description: >
    Create detailed and comprehensive educational content for {topic} based on the provided research, your existing knowledge, and content plan. The content should be
    tailored for a {audience_level} audience, explaining concepts thoroughly and at an appropriate level of complexity. Follow
    the content plan structure while ensuring the writing is engaging, technically accurate, and in-depth. Thoroughness, completeness, and depth are key.

    Section {section}
  expected_output: >
    A well-structured and comprehensive section that will be part of a longer form content piece that follows the 
    content plan and effectively teaches {topic} to {audience_level} level learners. Completeness, thoroughness, and depth are key. Use analogies,
    examples, and detailed explanations to help explain the content when appropriate.

    Ensure the content is formatted with clear headings and subheadings, and use bullet points where appropriate to enhance readability.

    No need to include summaries or conclusions of each section, just the content.
  agent: writer

editor_task:
  description: >
    Review and refine the written educational content for {topic}. Ensure it maintains high quality standards, follows the
    content plan precisely, and effectively communicates all learning objectives. Pay special attention to language level,
    examples, and explanations to verify they are appropriate for {audience_level} learners while preserving technical accuracy.
    Thoroughness, completeness, and depth are key.

    Section {section}
  expected_output: >
    A polished and comprehensive version of the educational content with improved clarity, appropriate complexity level, and enhanced readability
    for {audience_level} learners. Ensure the content is formatted with clear headings and subheadings, and use bullet points where appropriate to enhance readability.

    We only want the section content back, nothing else. Do not include the feedback.
  agent: editor

quality_task:
    description: >
      Perform a comprehensive quality assessment of the final educational content for {topic}. Evaluate against educational best
      practices and verify alignment with {audience_level} level expectations. Check that all sections from the content plan are
      covered adequately, concepts build logically, and learning objectives are met effectively. Thoroughness, completeness, and depth are key.

      Section {section}
    expected_output: >
      I want an improved and comprehensive version of the section content that incorporates the feedback. Ensure the content is formatted with clear headings and subheadings, and use bullet points where appropriate to enhance readability.
      Include references to the sources used in the summary created in @tasks.yaml. Additionally, ensure that references are included as inline citations or hyperlinks within the content where appropriate. Do not include the feedback itself, just the improved content.
    agent: quality_control

producer_task:
  description: >
    Manage the production of the educational content piece on {topic}, including the writer, editor, and quality agents.  You need to make sure they are communicating clearly
    and stay on task.
    
    Section {section}
  expected_output: >
    A high-quality educational content piece on {topic} that is both informative and engaging for {audience_level} audience.
  agent: producer
